// frontend/src/routes/credits/+page.svelte
<script lang="ts">
	import ArrowLeftIcon from 'lucide-svelte/icons/arrow-left';
</script>

<svelte:head>
	<title>Credits - Vortex</title>
</svelte:head>

<div class="container mx-auto flex w-4/5 flex-col justify-center gap-4 p-4 lg:w-1/2">
	<div>
		<h1 class="mb-2 text-3xl font-bold">Credits</h1>
		<p>Thank you to the following people for their contributions to Vortex:</p>
	</div>
	<ul class="list-disc">
		<li>
			<a href="https://pixelverse.tech/" target="_blank" class="underline">Hayden Kong/Pixelverse</a
			>
			for the
			<b>shadow.pixelverse.tech, assembly.pixelverse.tech, and corporate.pixelverse.tech</b> subdomains
		</li>
		<li>
			<a href="https://hackclub.com/" target="_blank" class="underline">Hack Club</a> for the
			<b>shadow.dino.icu, erdtree.dino.icu, and vortex.dino.icu</b> subdomains
		</li>
		<li>
			<a href="https://mattsoh.dev/" target="_blank" class="underline">Matthew Soh</a> for the
			<b>vortex.mattsoh.dev</b> subdomain
		</li>
		<li>
			<a href="https://nic.us.kg/" target="_blank" class="underline">us.kg</a> for the
			<b>postal.us.kg, postoffice.us.kg, and vortex.us.kg</b> domains
		</li>
		<li>
			<a href="https://ssmidge.xyz/" target="_blank" class="underline">Adrian T</a> for the
			<b>lunarhoax.com</b> domain <i>(side note: the domain isn't about the moon landing 😅)</i>
		</li>
		<li>
			<a href="https://jer.app/" target="_blank" class="underline">Jeremy Woolley</a> for the
			<b>comet.jer.app and cosmos.jer.app</b> subdomains
		</li>
		<li>
			<a href="https://matytyma.dev/" target="_blank" class="underline">matytyma</a> for the
			<b>vortex.matytyma.dev</b> subdomain
		</li>
		<li>
			<a href="https://matytyma.dev/" target="_blank" class="underline">The BBSS Hack Club</a> for
			the
			<b>shuttle.bbsshack.club</b> subdomain
		</li>
		<li>
			<a href="https://userexe.me/" target="_blank" class="underline">Dominic</a> for the
			<b>gambling.baby</b> domain
		</li>
		<li>
			<a href="https://whatisham.eu.org/" target="_blank" class="underline">Lucas</a> for the
			<b>whatisham.eu.org</b> subdomain
		</li>
	</ul>
	<hr class="my-4" />
	<a href="/" class="btn border-gray-300 p-1">
		<ArrowLeftIcon size="1.2rem" class="mr-2" />
		<p>Go back home...</p>
	</a>
</div>

// frontend/app/routes/credits.tsx
export default function Credits() {
    return (
        <div className="flex flex-col md:p-6 mx-auto prose">
            <h1 className="mb-0">Credits</h1>
            <p className="mb-0">Thank you to all the people who helped make this project possible!</p>

            <ul className="list-disc">
                <li>
                    <a href="https://pixelverse.tech/" target="_blank" className="underline">Hayden Kong/Pixelverse</a
                    >{" "}
                    for the{" "}
                    <b>shadow.pixelverse.tech, assembly.pixelverse.tech, and corporate.pixelverse.tech</b> subdomains
                </li>
                <li>
                    <a href="https://hackclub.com/" target="_blank" className="underline">Hack Club</a> for the{" "}
                    <b>shadow.dino.icu, erdtree.dino.icu, and vortex.dino.icu</b> subdomains
                </li>
                <li>
                    <a href="https://mattsoh.dev/" target="_blank" className="underline">Matthew Soh</a> for the{" "}
                    <b>vortex.mattsoh.dev</b> subdomain
                </li>
                <li>
                    <a href="https://ssmidge.xyz/" target="_blank" className="underline">Adrian T</a> for the{" "}
                    <b>lunarhoax.com</b> domain <i>(side note: the domain isn't about the moon landing 😅)</i>
                </li>
                <li>
                    <a href="https://jer.app/" target="_blank" className="underline">Jeremy Woolley</a> for the{" "}
                    <b>comet.jer.app and cosmos.jer.app</b> subdomains
                </li>
                <li>
                    <a href="https://matytyma.dev/" target="_blank" className="underline">matytyma</a> for the{" "}
                    <b>vortex.matytyma.dev</b> subdomain
                </li>
                <li>
                    <a href="https://matytyma.dev/" target="_blank" className="underline">The BBSS Hack Club</a> for the{" "}
                    <b>shuttle.bbsshack.club</b> subdomain
                </li>
                <li>
                    <a href="https://userexe.me/" target="_blank" className="underline">Dominic</a> for the{" "}
                    <b>gambling.baby</b> domain
                </li>
                <li>
                    <a href="https://whatisham.eu.org/" target="_blank" className="underline">Lucas</a> for the{" "}
                    <b>whatisham.eu.org</b> subdomain
                </li>
            </ul>

        </div>
    );
}
